### PR TITLE
Update to 1.0

### PR DESCRIPTION
**Pull request by ximion**

### CODE REVIEW

**Comment by ximion** [comment]
Flatpak builder seems to be complaining about missing screenshots... - but this is a console application, there are no screenshots!
A bit ironic that this seems to fail due to AppStream issues. @barthalion or @razzeee do you know what's going on here?
I also seem to get an error about missing icons, but for this console application, `skip-icons-check` is set to `true`, so there shouldn't be an error.

**Comment by razzeee** [comment]
I'm not sure, but the website itself only lists console apps, if they have an icon and at least one screenshot. Barth might have build that check additionally somewhere into the pipelines, but I'm not sure.

**Comment by ximion** [comment]
> I'm not sure, but the website itself only lists console apps, if they have an icon and at least one screenshot.

That doesn't seem to be the case: https://flathub.org/apps/org.freedesktop.appstream.cli

This also built just fine before, so this change does not make much sense to me... (at least not for anything that isn't a `desktop-application` component).

**Comment by razzeee** [comment]
While it gets a page (probably more of a bug),  it's not added to the search and other places

**Comment by ximion** [comment]
Screenshots make no sense here at all... I could maybe add an icon though. Should this be a blocker though to add `console-application` apps? This would affect a lot of stuff I'd imagine (like compilers and other things), and while it's probably fair to not display applications without icon in the store pages, excluding them from the repository entirely (especially since they are already in there) feels like it's a bit of an overreaction.

**Comment by razzeee** [comment]
I don't think this was meant to work like this, so it's probably a bug - let's wait for Barth

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
I need to poke around, but yes, this is a regression on our end.

**Comment by barthalion** [comment]
bot, build

**Comment by ximion** [comment]
Nice, thank you for the quick fix! Looks like the Flathub JSON file needs to be installed as well now?
@barthalion Is this safe to merge, or should I wait a bit? :-)

**Comment by barthalion** [comment]
Yeah, it's good to go.

**Comment by ximion** [comment]
> Yeah, it's good to go.

Excellent :-) This bundle is a pretty nice way for people to validate with newer AS versions (and use compose too!).

**Pull request merged**
